# Generated by Django 5.0.2 on 2024-02-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_ratings', '0002_song_spotify_id_alter_song_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='overall_rating',
            field=models.FloatField(default=0),
        ),
    ]
