# Generated by Django 5.0.2 on 2024-04-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_ratings', '0004_remove_song_id_alter_song_spotify_id'),
    ]

    operations = [
    migrations.AlterField(
        model_name='song',
        name='spotify_id',
        field=models.CharField(max_length=255, unique=True),
    ),
    migrations.AlterField(
        model_name='rating',
        name='song',
        field=models.ForeignKey(to='song_ratings.Song', to_field='spotify_id', on_delete=models.CASCADE),
    ),
]
