# Generated by Django 4.2.10 on 2024-04-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_ratings', '0004_remove_song_id_alter_song_spotify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='song',
            field=models.CharField(max_length=255),
        ),
    ]
