# Generated by Django 4.2.10 on 2024-04-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_ratings', '0005_alter_rating_song'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
