# Generated by Django 4.2.10 on 2024-04-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_ratings', '0006_alter_rating_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='song',
            new_name='song_id',
        ),
        migrations.AddField(
            model_name='song',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
