# Generated by Django 4.2.10 on 2024-04-11 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('song_ratings', '0007_rename_song_rating_song_id_song_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AddField(
            model_name='rating',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='song_ratings.song'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'song')},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='song_id',
        ),
    ]
